In [1]:
import pandas as pd
import numpy as np
# import matplotlib
# import matplotlib.pyplot as plt
# import keras
# from keras.models import load_model

In [3]:
feature_XGB_no_fillnan = pd.read_csv('data/XGB_FE2_No_fillNaN.csv')

In [4]:
feature_logistic_linear = pd.read_csv('log_reg_All_table_PCA_new_FE2.csv')

In [5]:
feature_FF = pd.read_csv('FF_DO_PCA_AUTO_CALSS_WEIGHT(0.779).csv')

In [6]:
feature_XGB_no_fillnan

       SK_ID_CURR    TARGET
0          100001  0.209332
1          100005  0.413568
2          100013  0.082060
3          100028  0.078315
4          100038  0.362769
5          100042  0.196000
6          100057  0.040987
7          100065  0.113212
8          100066  0.090455
9          100067  0.358401
10         100074  0.141001
11         100090  0.132989
12         100091  0.472308
13         100092  0.267056
14         100106  0.161589
15         100107  0.317347
16         100109  0.191648
17         100117  0.066361
18         100128  0.260037
19         100141  0.088838
20         100150  0.125934
21         100168  0.073749
22         100169  0.164427
23         100170  0.487392
24         100171  0.133514
25         100172  0.380797
26         100184  0.203882
27         100187  0.252362
28         100212  0.110864
29         100222  0.098705
...           ...       ...
48714      455963  0.107755
48715      455965  0.044268
48716      456007  0.536296
48717      456008  0.052409
48718      456009  0.146130
48719      456010  0.239721
48720      456011  0.105820
48721      456013  0.381151
48722      456028  0.328164
48723      456058  0.296729
48724      456111  0.311668
48725      456114  0.222831
48726      456115  0.147705
48727      456116  0.032860
48728      456119  0.044666
48729      456120  0.355387
48730      456122  0.205322
48731      456123  0.056838
48732      456166  0.261908
48733      456167  0.155433
48734      456168  0.151547
48735      456169  0.370885
48736      456170  0.061992
48737      456189  0.418815
48738      456202  0.296538
48739      456221  0.117799
48740      456222  0.175847
48741      456223  0.042937
48742      456224  0.085544
48743      456250  0.476731

[48744 rows x 2 columns]

In [7]:
feature_logistic_linear

       SK_ID_CURR    TARGET
0          100001  0.113004
1          100005  0.197508
2          100013  0.082530
3          100028  0.133011
4          100038  0.193297
5          100042  0.105219
6          100057  0.097769
7          100065  0.157232
8          100066  0.105205
9          100067  0.181926
10         100074  0.122086
11         100090  0.178868
12         100091  0.189506
13         100092  0.161875
14         100106  0.151346
15         100107  0.182755
16         100109  0.137737
17         100117  0.091085
18         100128  0.170095
19         100141  0.109622
20         100150  0.104969
21         100168  0.083823
22         100169  0.137415
23         100170  0.157765
24         100171  0.093579
25         100172  0.186761
26         100184  0.157469
27         100187  0.152484
28         100212  0.127176
29         100222  0.151866
...           ...       ...
48714      455963  0.126033
48715      455965  0.104033
48716      456007  0.213941
48717      456008  0.088893
48718      456009  0.136945
48719      456010  0.156740
48720      456011  0.126523
48721      456013  0.183107
48722      456028  0.185952
48723      456058  0.170643
48724      456111  0.175289
48725      456114  0.144173
48726      456115  0.121143
48727      456116  0.131956
48728      456119  0.089754
48729      456120  0.151804
48730      456122  0.158629
48731      456123  0.086200
48732      456166  0.176988
48733      456167  0.120824
48734      456168  0.164103
48735      456169  0.123649
48736      456170  0.086080
48737      456189  0.162534
48738      456202  0.171078
48739      456221  0.117034
48740      456222  0.131943
48741      456223  0.126504
48742      456224  0.138724
48743      456250  0.208381

[48744 rows x 2 columns]

In [8]:
feature_FF

       SK_ID_CURR    TARGET
0          100001  0.038111
1          100005  0.215990
2          100013  0.049039
3          100028  0.016567
4          100038  0.184306
5          100042  0.087685
6          100057  0.017118
7          100065  0.042681
8          100066  0.004863
9          100067  0.217079
10         100074  0.029050
11         100090  0.025490
12         100091  0.174348
13         100092  0.038948
14         100106  0.038839
15         100107  0.168405
16         100109  0.055624
17         100117  0.027857
18         100128  0.073551
19         100141  0.047915
20         100150  0.032793
21         100168  0.004503
22         100169  0.054900
23         100170  0.303268
24         100171  0.028146
25         100172  0.156139
26         100184  0.090075
27         100187  0.036432
28         100212  0.012082
29         100222  0.027310
...           ...       ...
48714      455963  0.007449
48715      455965  0.017380
48716      456007  0.356835
48717      456008  0.005681
48718      456009  0.055714
48719      456010  0.115091
48720      456011  0.032274
48721      456013  0.178628
48722      456028  0.141564
48723      456058  0.097405
48724      456111  0.108486
48725      456114  0.068943
48726      456115  0.021555
48727      456116  0.009909
48728      456119  0.004501
48729      456120  0.103080
48730      456122  0.177885
48731      456123  0.006565
48732      456166  0.107240
48733      456167  0.044779
48734      456168  0.081487
48735      456169  0.098531
48736      456170  0.008521
48737      456189  0.085760
48738      456202  0.078379
48739      456221  0.067679
48740      456222  0.057818
48741      456223  0.023798
48742      456224  0.041596
48743      456250  0.105280

[48744 rows x 2 columns]

In [43]:
ffw = 65
llw = 0
xgbw = 35

sumw = ffw + llw + xgbw

In [44]:
ensemble = feature_FF.copy()
ensemble['TARGET'] = ((feature_FF['TARGET']*ffw) + (feature_logistic_linear['TARGET']*llw) + (feature_XGB_no_fillnan['TARGET']*xgbw))/sumw

In [45]:
ensemble

       SK_ID_CURR    TARGET
0          100001  0.089477
1          100005  0.275263
2          100013  0.058945
3          100028  0.035092
4          100038  0.237845
5          100042  0.120180
6          100057  0.024279
7          100065  0.063840
8          100066  0.030541
9          100067  0.259476
10         100074  0.062635
11         100090  0.057740
12         100091  0.263736
13         100092  0.107381
14         100106  0.075664
15         100107  0.213088
16         100109  0.096431
17         100117  0.039409
18         100128  0.129497
19         100141  0.060192
20         100150  0.060735
21         100168  0.025277
22         100169  0.087758
23         100170  0.358505
24         100171  0.059757
25         100172  0.223536
26         100184  0.124217
27         100187  0.101211
28         100212  0.041717
29         100222  0.048729
...           ...       ...
48714      455963  0.037540
48715      455965  0.025447
48716      456007  0.410673
48717      456008  0.019699
48718      456009  0.082839
48719      456010  0.152480
48720      456011  0.054338
48721      456013  0.239385
48722      456028  0.197544
48723      456058  0.157202
48724      456111  0.169440
48725      456114  0.115109
48726      456115  0.059400
48727      456116  0.016794
48728      456119  0.016550
48729      456120  0.178772
48730      456122  0.186116
48731      456123  0.021647
48732      456166  0.153641
48733      456167  0.077975
48734      456168  0.102505
48735      456169  0.180237
48736      456170  0.024562
48737      456189  0.185676
48738      456202  0.143827
48739      456221  0.082715
48740      456222  0.093227
48741      456223  0.029540
48742      456224  0.054780
48743      456250  0.216715

[48744 rows x 2 columns]

In [46]:
ensemble.to_csv('ensem_65_0_35.csv', index=False)